#!/usr/bin/env python3
from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from datetime import datetime, UTC
import json
from pathlib import Path
import re
import sys
from typing import Any, Iterable


REPO_ROOT = Path(__file__).resolve().parents[4]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from triage_state import load_state, save_state


SOURCE_EXTENSIONS = {".java", ".kt", ".kts", ".scala", ".groovy", ".xml", ".properties", ".yml", ".yaml"}
CLASS_PATTERN = re.compile(r"\b(?:class|interface|enum)\s+([A-Z][A-Za-z0-9_]*)")
METHOD_PATTERN = re.compile(
    r"\b(?:public|protected|private|static|final|synchronized|abstract|\s)+"
    r"[\w<>\[\], ?]+\s+([A-Za-z_][A-Za-z0-9_]*)\s*\("
)
EXCEPTION_PATTERN = re.compile(r"\b([A-Z][A-Za-z0-9_]*(?:Exception|Error))\b")
PASCAL_PATTERN = re.compile(r"\b([A-Z][A-Za-z0-9_]{3,})\b")
LOG_MESSAGE_PATTERN = re.compile(
    r"\blog\.(?:trace|debug|info|warn|error)\s*\(\s*\"([^\"]{4,220})\"",
    flags=re.IGNORECASE,
)
GENERATED_MARKERS = (
    "Generated by the protocol buffer compiler",
    "GeneratedMessageV3",
    "@Generated",
    "do not edit",
)
IGNORED_TERM_NAMES = {
    "String",
    "Object",
    "Boolean",
    "Integer",
    "Builder",
    "RuntimeException",
    "Request",
    "Response",
    "success",
    "fail",
    "apply",
    "cancel",
    "destroy",
    "init",
    "connect",
    "execute",
    "information",
}
GENERIC_CODE_SEEDS = {
    "IDLE",
    "PROCESSING",
    "EXECUTING",
    "RAW",
    "IN_QUEUE",
    "ASSIGN_NEXT_SUB_TASK",
    "ONES",
    "RIOT",
    "GSEO",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Extract code-derived keyword hints for RIOT log triage.",
    )
    parser.add_argument("--state", default="", help="Path to 00-state.json.")
    parser.add_argument("--code-root", default="", help="Source repository root. Defaults to active project worktree in state.project_workspace.")
    parser.add_argument("--keyword-package-file", default="", help="Existing keyword package to use as seed terms.")
    parser.add_argument("--output-dir", default="", help="Where code_keyword_hints.json is written.")
    parser.add_argument("--max-files", type=int, default=80, help="Maximum matched source files to inspect.")
    parser.add_argument("--max-terms", type=int, default=40, help="Maximum ranked terms to keep.")
    return parser.parse_args()


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def dedupe(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        item = str(value or "").strip()
        if not item or item in seen:
            continue
        seen.add(item)
        result.append(item)
    return result


def extract_pascal_terms(text: str) -> list[str]:
    ignored = {"INFO", "WARN", "ERROR", "DEBUG", "UTC", "RIOT", "HTTP"}
    return [term for term in PASCAL_PATTERN.findall(text or "") if term not in ignored]


def seed_terms_from_state(state: dict[str, Any], package: dict[str, Any]) -> list[str]:
    fragments = [
        state.get("current_question", ""),
        state.get("primary_question", ""),
        " ".join(state.get("hypotheses") or []),
        " ".join(state.get("module_hypothesis") or []),
        " ".join(str(value) for value in dict(state.get("incident_snapshot") or {}).values()),
    ]
    package_terms = []
    for key in ("gate_terms", "core_terms", "exception_terms", "generic_terms", "include_terms"):
        package_terms.extend(str(item).strip() for item in package.get(key) or [])
    extracted = []
    for fragment in fragments:
        extracted.extend(extract_pascal_terms(str(fragment or "")))
    return [term for term in dedupe([*package_terms, *extracted]) if is_useful_code_seed(term)]


def is_useful_code_seed(term: str) -> bool:
    item = str(term or "").strip()
    if len(item) < 3:
        return False
    if item in GENERIC_CODE_SEEDS:
        return False
    if item.lower().startswith("riot"):
        return False
    if re.fullmatch(r"[A-Za-z0-9]{12,}", item) and re.search(r"\d", item):
        return False
    if re.fullmatch(r"\d{5,}", item):
        return False
    if re.fullmatch(r"AG\d+", item, flags=re.IGNORECASE):
        return False
    lowered = item.lower()
    if lowered.startswith(("httpact_", "move_")):
        return False
    if lowered.startswith("node-map"):
        return False
    if re.search(r"_[0-9a-f]{8,}", lowered):
        return False
    if re.search(r"[\u4e00-\u9fff]", item):
        return True
    if "." in item:
        return True
    if re.search(r"[A-Z]", item) and re.search(r"[a-z]", item):
        return True
    if item.endswith(("Request", "Response", "Manager", "Service", "Action", "Exception", "Error")):
        return True
    return False


def source_files(root: Path) -> list[Path]:
    files = [path for path in root.rglob("*") if path.is_file() and path.suffix.lower() in SOURCE_EXTENSIONS]
    files.sort(key=lambda path: str(path.relative_to(root)).lower())
    return files


def score_source_files(root: Path, seeds: list[str], *, max_files: int) -> list[tuple[int, Path, str]]:
    scored: list[tuple[int, Path, str]] = []
    lowered_seeds = [seed.lower() for seed in seeds if len(seed) >= 3]
    if not lowered_seeds:
        return []
    for path in source_files(root):
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if should_skip_source(path, text):
            continue
        lowered = text.lower()
        score = sum(lowered.count(seed) for seed in lowered_seeds)
        if score <= 0:
            continue
        scored.append((score, path, text))
    scored.sort(key=lambda item: (item[0], -len(str(item[1]))), reverse=True)
    return scored[:max_files]


def should_skip_source(path: Path, text: str) -> bool:
    lowered_path = str(path).lower().replace("\\", "/")
    if any(part in lowered_path for part in ("/target/", "/build/", "/generated/", "/.gradle/", "/src/test/")):
        return True
    if path.name.endswith("Protos.java") or path.name.endswith("Proto.java"):
        return True
    lowered_text = text[:20000].lower()
    return any(marker.lower() in lowered_text for marker in GENERATED_MARKERS)


def term_category(term: str) -> str:
    if term.endswith(("Exception", "Error")):
        return "exception"
    if term and term[0].isupper():
        return "class"
    return "method"


def score_terms(scored_files: list[tuple[int, Path, str]], root: Path, seeds: list[str], *, max_terms: int) -> list[dict[str, Any]]:
    scores: Counter[str] = Counter()
    categories: dict[str, str] = {}
    reasons: dict[str, set[str]] = defaultdict(set)
    samples: dict[str, list[dict[str, Any]]] = defaultdict(list)
    lowered_seeds = [seed.lower() for seed in seeds if len(seed) >= 4]

    for file_score, path, text in scored_files:
        rel_path = str(path.relative_to(root))
        candidate_terms: dict[str, tuple[str, int]] = {}
        for term in CLASS_PATTERN.findall(text):
            candidate_terms[term] = ("class", max(candidate_terms.get(term, ("", 0))[1], 24))
        for term in EXCEPTION_PATTERN.findall(text):
            candidate_terms[term] = ("exception", max(candidate_terms.get(term, ("", 0))[1], 32))
        for term in METHOD_PATTERN.findall(text):
            if is_low_value_method(term):
                continue
            if candidate_terms.get(term, ("", 0))[0] == "exception":
                continue
            candidate_terms[term] = ("method", max(candidate_terms.get(term, ("", 0))[1], 14))

        for term, (category, base_score) in candidate_terms.items():
            if len(term) < 4 or term in IGNORED_TERM_NAMES:
                continue
            term_lower = term.lower()
            occurrence_bonus = min(text.count(term), 3) * 2
            seed_bonus = 0
            if any(seed in term_lower or term_lower in seed for seed in lowered_seeds):
                seed_bonus += 30
            if term_lower in str(path.name).lower():
                seed_bonus += 18
            score = base_score + min(file_score, 20) + occurrence_bonus + seed_bonus
            scores[term] += score
            if category == "exception" or term not in categories:
                categories[term] = category
            reasons[term].add(f"{category} in {rel_path}")
            if len(samples[term]) < 3:
                samples[term].append({"path": rel_path, "file_score": file_score})

    ranked: list[dict[str, Any]] = []
    for term, score in scores.most_common(max_terms):
        category = categories.get(term) or term_category(term)
        ranked.append({
            "term": term,
            "score": int(score),
            "category": category,
            "reason": "; ".join(sorted(reasons.get(term) or []))[:300],
            "samples": samples.get(term) or [],
        })
    return ranked


def score_log_messages(scored_files: list[tuple[int, Path, str]], root: Path, seeds: list[str], *, max_terms: int) -> list[dict[str, Any]]:
    scores: Counter[str] = Counter()
    reasons: dict[str, set[str]] = defaultdict(set)
    lowered_seeds = [seed.lower() for seed in seeds if len(seed) >= 4]
    for file_score, path, text in scored_files:
        rel_path = str(path.relative_to(root))
        for raw_message in LOG_MESSAGE_PATTERN.findall(text):
            message = normalize_log_message(raw_message)
            if not message:
                continue
            score = 20 + min(file_score, 20)
            lowered = message.lower()
            if any(seed in lowered or lowered in seed for seed in lowered_seeds):
                score += 20
            scores[message] += score
            reasons[message].add(f"log message in {rel_path}")
    return [
        {
            "term": term,
            "score": int(score),
            "category": "log_message",
            "reason": "; ".join(sorted(reasons.get(term) or []))[:300],
        }
        for term, score in scores.most_common(max_terms)
    ]


def extract_class_log_messages(scored_files: list[tuple[int, Path, str]], root: Path, seeds: list[str], *, max_items: int) -> list[dict[str, Any]]:
    lowered_seeds = [seed.lower() for seed in seeds if len(seed) >= 4]
    items: list[dict[str, Any]] = []
    for file_score, path, text in scored_files:
        rel_path = str(path.relative_to(root))
        class_terms = [term for term in CLASS_PATTERN.findall(text) if term not in IGNORED_TERM_NAMES]
        method_terms = [
            term for term in METHOD_PATTERN.findall(text)
            if len(term) >= 4 and term not in IGNORED_TERM_NAMES and not is_low_value_method(term)
        ]
        exception_terms = [
            term for term in EXCEPTION_PATTERN.findall(text)
            if term not in IGNORED_TERM_NAMES
        ]
        log_messages = dedupe(
            normalize_log_message(message)
            for message in LOG_MESSAGE_PATTERN.findall(text)
        )
        log_messages = [message for message in log_messages if message]
        if not class_terms and not log_messages:
            continue
        relevance = file_score
        joined = " ".join([*class_terms, *method_terms, *exception_terms, *log_messages]).lower()
        relevance += sum(10 for seed in lowered_seeds if seed in joined)
        items.append({
            "path": rel_path,
            "score": int(relevance),
            "classes": dedupe(class_terms)[:8],
            "methods": dedupe(method_terms)[:12],
            "exception_terms": dedupe(exception_terms)[:8],
            "log_message_terms": log_messages[:12],
        })
    items.sort(key=lambda item: int(item.get("score") or 0), reverse=True)
    return items[:max_items]


def normalize_log_message(raw_message: str) -> str:
    message = " ".join(str(raw_message or "").split())
    message = re.sub(r"\{\}", "", message).strip(" :-")
    if len(message) < 4:
        return ""
    if message.lower() in {"success", "failed", "error"}:
        return ""
    return message[:160]


def is_low_value_method(term: str) -> bool:
    if term in {"toString", "equals", "hashCode", "valueOf", "builder", "newBuilder"}:
        return True
    if re.match(r"^(get|set|clear|has|add|remove)[A-Z0-9_].{0,12}$", term):
        return True
    return False


def build_hints(*, state: dict[str, Any], package: dict[str, Any], code_root: Path, max_files: int, max_terms: int) -> dict[str, Any]:
    seeds = seed_terms_from_state(state, package)
    scored_files = score_source_files(code_root, seeds, max_files=max_files)
    ranked_terms = score_terms(scored_files, code_root, seeds, max_terms=max_terms)
    ranked_log_messages = score_log_messages(scored_files, code_root, seeds, max_terms=20)
    class_log_messages = extract_class_log_messages(scored_files, code_root, seeds, max_items=12)
    core_terms = [
        item["term"]
        for item in ranked_terms
        if item.get("category") in {"class", "method"}
    ][:20]
    exception_terms = [
        item["term"]
        for item in ranked_terms
        if item.get("category") == "exception"
    ][:10]
    log_message_terms = [item["term"] for item in ranked_log_messages[:10]]
    return {
        "generated_at": datetime.now(UTC).isoformat(timespec="seconds").replace("+00:00", "Z"),
        "code_root": str(code_root.resolve()),
        "seed_terms": seeds,
        "files_considered": len(scored_files),
        "top_files": [
            {"path": str(path.relative_to(code_root)), "score": score}
            for score, path, _ in scored_files[:10]
        ],
        "core_terms": core_terms,
        "exception_terms": exception_terms,
        "log_message_terms": log_message_terms,
        "class_log_messages": class_log_messages,
        "term_priorities": ranked_terms,
        "log_message_priorities": ranked_log_messages,
        "next_keyword_adjustments": {
            "core_terms": core_terms[:10],
            "exception_terms": exception_terms[:5],
            "log_message_terms": log_message_terms[:5],
            "term_priorities": [
                {
                    "term": item["term"],
                    "score": item["score"],
                    "category": item["category"],
                    "reason": item["reason"],
                }
                for item in ranked_terms[:20]
            ] + ranked_log_messages[:10],
        },
    }


def resolve_code_root(args: argparse.Namespace, state: dict[str, Any]) -> Path:
    if args.code_root:
        return Path(args.code_root).resolve()
    workspace = dict(state.get("project_workspace") or {})
    projects = workspace.get("projects") if isinstance(workspace.get("projects"), dict) else {}
    active_project = str(workspace.get("active_project") or state.get("project") or "").strip()
    runtime = (
        dict(projects.get(active_project) or {})
        if isinstance(projects, dict) and active_project
        else {}
    )
    if not runtime and isinstance(projects, dict):
        for value in projects.values():
            if isinstance(value, dict):
                runtime = dict(value)
                break
    for key in ("worktree_path", "execution_path", "recommended_worktree", "project_path"):
        value = str(runtime.get(key) or "").strip()
        if value:
            return Path(value).resolve()
    raise SystemExit("Provide --code-root or state.project_workspace active project worktree.")


def main() -> int:
    args = parse_args()
    state_path = Path(args.state).resolve() if args.state else None
    state = load_state(state_path) if state_path else {}
    package = load_json(Path(args.keyword_package_file).resolve()) if args.keyword_package_file else {}
    code_root = resolve_code_root(args, state)
    if not code_root.exists():
        raise SystemExit(f"Code root does not exist: {code_root}")
    output_dir = Path(args.output_dir).resolve() if args.output_dir else (state_path.parent if state_path else Path.cwd())
    output_dir.mkdir(parents=True, exist_ok=True)

    hints = build_hints(
        state=state,
        package=package,
        code_root=code_root,
        max_files=args.max_files,
        max_terms=args.max_terms,
    )
    output_path = output_dir / "code_keyword_hints.json"
    output_path.write_text(json.dumps(hints, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if state_path:
        state = load_state(state_path)
        search_artifacts = dict(state.get("search_artifacts") or {})
        search_artifacts["last_code_keyword_hints"] = str(output_path)
        state["search_artifacts"] = search_artifacts
        save_state(state_path, state)
    print(json.dumps({"code_keyword_hints": str(output_path), **hints}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
